2024-05-07 14:18:20 | INFO | model_worker | Loading the model mplug-owl2-llama2-7b on worker cdd720 ...
2024-05-07 14:18:20 | ERROR | stderr | tokenizer_config.json:   0%|                                     | 0.00/263 [00:00<?, ?B/s]
2024-05-07 14:18:20 | ERROR | stderr | tokenizer_config.json: 749B [00:00, 5.95MB/s]
2024-05-07 14:18:20 | ERROR | stderr | 
2024-05-07 14:18:22 | ERROR | stderr | tokenizer.model:   0%|                                          | 0.00/500k [00:00<?, ?B/s]
2024-05-07 14:18:25 | ERROR | stderr | tokenizer.model: 100%|███████████████████████████████████| 500k/500k [00:02<00:00, 174kB/s]
2024-05-07 14:18:25 | ERROR | stderr | tokenizer.model: 100%|███████████████████████████████████| 500k/500k [00:02<00:00, 174kB/s]
2024-05-07 14:18:25 | ERROR | stderr | 
2024-05-07 14:18:25 | ERROR | stderr | Traceback (most recent call last):
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-05-07 14:18:25 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/runpy.py", line 86, in _run_code
2024-05-07 14:18:25 | ERROR | stderr |     exec(code, run_globals)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/work/deep_learning/codes_from_github/large-models/mPLUG-Owl/mPLUG-Owl2/mplug_owl2/local_serve/local_web_server.py", line 381, in <module>
2024-05-07 14:18:25 | ERROR | stderr |     model = ModelWorker(args.model_path, None, None, args.load_8bit, args.load_4bit, args.device)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/work/deep_learning/codes_from_github/large-models/mPLUG-Owl/mPLUG-Owl2/mplug_owl2/local_serve/model_worker.py", line 45, in __init__
2024-05-07 14:18:25 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/work/deep_learning/codes_from_github/large-models/mPLUG-Owl/mPLUG-Owl2/mplug_owl2/model/builder.py", line 105, in load_pretrained_model
2024-05-07 14:18:25 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
2024-05-07 14:18:25 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1800, in from_pretrained
2024-05-07 14:18:25 | ERROR | stderr |     resolved_vocab_files[file_id] = cached_file(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/transformers/utils/hub.py", line 417, in cached_file
2024-05-07 14:18:25 | ERROR | stderr |     resolved_file = hf_hub_download(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2024-05-07 14:18:25 | ERROR | stderr |     return fn(*args, **kwargs)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1247, in hf_hub_download
2024-05-07 14:18:25 | ERROR | stderr |     metadata = get_hf_file_metadata(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
2024-05-07 14:18:25 | ERROR | stderr |     return fn(*args, **kwargs)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1624, in get_hf_file_metadata
2024-05-07 14:18:25 | ERROR | stderr |     r = _request_wrapper(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 402, in _request_wrapper
2024-05-07 14:18:25 | ERROR | stderr |     response = _request_wrapper(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 425, in _request_wrapper
2024-05-07 14:18:25 | ERROR | stderr |     response = get_session().request(method=method, url=url, **params)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
2024-05-07 14:18:25 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
2024-05-07 14:18:25 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
2024-05-07 14:18:25 | ERROR | stderr |     return super().send(request, *args, **kwargs)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
2024-05-07 14:18:25 | ERROR | stderr |     resp = conn.urlopen(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
2024-05-07 14:18:25 | ERROR | stderr |     response = self._make_request(
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
2024-05-07 14:18:25 | ERROR | stderr |     response = conn.getresponse()
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
2024-05-07 14:18:25 | ERROR | stderr |     httplib_response = super().getresponse()
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/http/client.py", line 1375, in getresponse
2024-05-07 14:18:25 | ERROR | stderr |     response.begin()
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/http/client.py", line 318, in begin
2024-05-07 14:18:25 | ERROR | stderr |     version, status, reason = self._read_status()
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/http/client.py", line 279, in _read_status
2024-05-07 14:18:25 | ERROR | stderr |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/socket.py", line 705, in readinto
2024-05-07 14:18:25 | ERROR | stderr |     return self._sock.recv_into(b)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/ssl.py", line 1307, in recv_into
2024-05-07 14:18:25 | ERROR | stderr |     return self.read(nbytes, buffer)
2024-05-07 14:18:25 | ERROR | stderr |   File "/home/zeyu/anaconda3/envs/mplug-owl2/lib/python3.10/ssl.py", line 1163, in read
2024-05-07 14:18:25 | ERROR | stderr |     return self._sslobj.read(len, buffer)
2024-05-07 14:18:25 | ERROR | stderr | KeyboardInterrupt
